package tests

import (
	heap "dataStruct/src/heap"
	"testing"
)

func TestMaxHeap(t *testing.T) {
	//maxHeap := heap.NewMaxHeap(10)
	//maxHeap.PileUp(1)
	//maxHeap.PileUp(203)
	//maxHeap.PileUp(3)
	//maxHeap.PileUp(80)
	//maxHeap.PileUp(29)
	//maxHeap.PileUp(1001)
	//maxHeap.PileUp(-20)
	//maxHeap.PileUp(99)
	//t.Log(maxHeap.Travel())
	tt := heap.NewMaxHeapWithData([]int{1, 2, 3, 4, 5, 2323, 1, -1, 90000, 23, 4})
	t.Log(tt.Travel())
	//maxHeap.PileDown()
	//maxHeap.PileDown()
	//maxHeap.PileDown()
	//maxHeap.PileDown()
	//maxHeap.PileDown()
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	t.Log(tt.PileDown())
	//t.Log(maxHeap.PileDown())
	//t.Log(maxHeap.PileDown())
	//t.Log(maxHeap.PileDown())
	//maxHeap.PileUp(20)
	//maxHeap.PileUp(40)
	//maxHeap.PileUp(60)
	//maxHeap.PileUp(80)
	//maxHeap.PileUp(61)
}

func TestMinHeap(t *testing.T) {
	maxHeap := heap.NewMinHeap(10)
	maxHeap.PileUp(1)
	maxHeap.PileUp(203)
	maxHeap.PileUp(3)
	maxHeap.PileUp(80)
	maxHeap.PileUp(29)
	maxHeap.PileUp(1001)
	maxHeap.PileUp(-20)
	maxHeap.PileUp(99)
	t.Log(maxHeap.Travel())
	//maxHeap.PileDown()
	//maxHeap.PileDown()
	//maxHeap.PileDown()
	//maxHeap.PileDown()
	//maxHeap.PileDown()
	t.Log(maxHeap.PileDown())
	t.Log(maxHeap.PileDown())
	t.Log(maxHeap.PileDown())
	t.Log(maxHeap.PileDown())
	t.Log(maxHeap.PileDown())
	t.Log(maxHeap.PileDown())
	t.Log(maxHeap.PileDown())
	t.Log(maxHeap.PileDown())
	//maxHeap.PileUp(20)
	//maxHeap.PileUp(40)
	//maxHeap.PileUp(60)
	//maxHeap.PileUp(80)
	//maxHeap.PileUp(61)
}
